### ISSUE TITLE
sh train.sh got error chamfer_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass

### ISSUE THREAD

**Issue by jiayaozhang** [AntheaLi/3DPartAssembly#17]
![image](https://user-images.githubusercontent.com/38579506/107555068-c912c500-6be7-11eb-92c8-03d8f3632e38.png)

I don't know how to solve this error, can anyone help?

**Comment by AntheaLi** [comment]
you will need to build chamfer_distance extension first. 
`cd exps/utils/cd`
`python setup.py install`
