### ISSUE TITLE
How to visualize the util->exps->3DPartAssembly

### ISSUE THREAD

**Issue by jiayaozhang** [AntheaLi/3DPartAssembly#18]
Would you mind provide a script on how to visualize the blender 

in /3DPartAssembly/exps/utils

sth might work like 
blender --background boxes.blend --python render_one_boxshape.py -- example_boxshape.json example_boxshape.png?

**Comment by AntheaLi** [comment]
you don't need to run blender by yourself, the visualization code automatically does that for you.

**Comment by jiayaozhang** [comment]
Greatly thanks for your patience and swift reply.
which one is the visualization code?
so could we directly run render_blender.py or render_using_blender.py ?
Since I run : python render_blender.py
it shows that No module named 'bpy', is that means I should run the codes under the blender-2.7.9 -> 2.79-> python folder ?

**Comment by jiayaozhang** [comment]
After training, I got 3480 checkpt.pth and net_network.pth
So we should visualize here?

**Comment by AntheaLi** [comment]
You will need to install bpy. 
`pip install bpy`

blender could be more difficult to work with sometimes, you can also check out other visualization methods such as matplotlib.

**Comment by jiayaozhang** [comment]
In StructureNet, there have three scripts

blender --background boxes.blend --python render_one_boxshape.py -- example_boxshape.json example_boxshape.png
blender --background point_clouds.blend --python render_one_pc.py -- example_pc.pts example_pc.png
blender --background point_clouds.blend --python render_one_pc_same_color.py --example_pc.ptsexample_pc_same_color.png

So I am wondering if 3DPartAssembly has the same scripts?
like:

blender -noaudio --background object_centered.blend --python render_blender.py data.npy data.png
lender -noaudio --background camera_centered.blend --python render_blender.py cube.obj  anchor.pts

If we know the scripts which might be easy to visualize, and I think it is not so hard for me to modify the code from blender 2.79 to blender 2.91.
And for the training process, I think we can use https://github.com/lanpa/tensorboardX for visualization.

**Comment by daerduoCarey** [comment]
structurenet code and this 3dpartassembly codebase both use blender 2.79b. There will be problems if you upgrade to 2.91. So I recommend using 2.79b.

**Comment by jiayaozhang** [comment]
Thanks for AntheaLi and daerduoCarey's reply and patience! I think I got it!
