### ISSUE TITLE
Re-congif on_kaichun_machine=conf.on_kaichun_machine how to change it suggestions

### ISSUE THREAD

**Issue by albertotono** [AntheaLi/3DPartAssembly#3]
Dear all, 

I am trying to modify your parameters including **data_path, exp_name and etc**.
when I go here
https://github.com/AntheaLi/3DPartAssembly/blob/master/exps/exp_segmentation/train.sh 

![Screenshot from 2020-10-26 12-07-02](https://user-images.githubusercontent.com/11828200/97216989-d82e4e00-1783-11eb-84a4-1707c7cbab00.png)

that refers the **train.py**

**max_num_mask = conf.max_num_parts, max_num_similar_parts=conf.max_num_similar_parts, img_size=conf.img_size, on_kaichun_machine=**conf.on_kaichun_machine**)**

https://github.com/AntheaLi/3DPartAssembly/blob/7c63d0269a182133b690d1aa41f681e47e2dcad3/exps/exp_segmentation/train.py#L28

not sure what should I change, any suggestions?

**Comment by albertotono** [comment]
Ok it seems that I will need to modify this https://github.com/AntheaLi/3DPartAssembly/blob/master/exps/exp_segmentation/data.py 
any support will be much appreciated.

**Comment by albertotono** [comment]
ok I had to install also 

`pip install h5py`
`pip install progressbar`

and then I got this 

```
Traceback (most recent call last):
  File "./train.py", line 378, in <module>
    os.mkdir(conf.exp_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'logs/exp-Table-mixed-model-'
```

it seems I need to edit `exp_dir`

**Comment by albertotono** [comment]
Is it possible that the `exp_dir` is the `**-exp_suffix '' \**`?
or is the `data_dir`?

i don't think it is one of those actually. But unfortunately I can see exp_dir only in train.py
![Screenshot from 2020-10-26 12-59-12](https://user-images.githubusercontent.com/11828200/97222169-2b57cf00-178b-11eb-9517-4a5a792da5b8.png)
reading the code it seems that it should create this folder, so I am not sure why it is not reading the `logs/exp-Table-mixed-model`

**Comment by AntheaLi** [comment]
Sorry for the confusion. I just removed that argument. Accidentally, left some legacy code in there.
