### ISSUE TITLE
Speficification for sh train.sh 

### ISSUE THREAD

**Issue by albertotono** [AntheaLi/3DPartAssembly#5]
in the guide you said
"modify your parameters including data_path, exp_name and **etc."**

**cd exps/exp_segmentation
sh train.sh** 

would you mind be more specific regarding what we should change please?

**Comment by albertotono** [comment]
```
python ./train.py  \
    --exp_suffix '' \
    --category Table-mixed \
    --device 0 \
    --model_version model \
    --num_epoch_every_visu 1 \
    --num_batch_every_visu 1 \
    --epochs 100000 \
    --overwrite \
    --data_dir '' \
    --lr_decay_every 5000
```

should we change the 

```
    --data_dir ''/home/alberto/Documents/3DPartAssembly/exps/utils/cd/assembly_data \
```
?

**Comment by albertotono** [comment]
the assembly data are 160GB in .zip 
![Screenshot from 2020-10-29 09-27-47](https://user-images.githubusercontent.com/11828200/97602865-0d77ad80-19c9-11eb-85c9-342df45a2225.png)
should we extract the .zip?

**Comment by AntheaLi** [comment]
yes, you should extract the zip
